Initialize model
TJCatFood/backend pull request #12
Opened 2020-11-12 12:33 UTC by Major-333

Initialize model

2020-11-12 13:26 UTC, DarkKowalski requested changes
Refine the code

2020-11-12 13:26 UTC, DarkKowalski commented on catfood/contest/models.py
> +    startTime = models.DateTimeField()
统一命名规则

2020-11-12 13:26 UTC, DarkKowalski commented on catfood/contest/models.py
> +    question_type = models.IntegerField(default=0)
加注释

2020-11-12 13:26 UTC, DarkKowalski commented on catfood/courseDataBase/models.py
> +    question_choice_a_content = models.CharField(max_length=20)
question_content max_length 改成 512
question_choice_a/b/c/d_content max_length 改成 256

2020-11-12 13:26 UTC, DarkKowalski commented on catfood/grade/models.py
> +    assignmentPoint = models.IntegerField(null=True)
统一命名规则

2020-11-12 13:26 UTC, DarkKowalski commented on catfood/grade/models.py
> +    assignmentPoint = models.DecimalField(max_digits=5, decimal_places=2, null=True)
统一命名规则

2020-11-12 13:26 UTC, DarkKowalski commented on catfood/grade/models.py
> +    combat = models.DecimalField(max_digits=5, decimal_places=2, null=True)
这里使用的是 contest 不是 combat

2020-11-12 13:26 UTC, DarkKowalski commented on catfood/lecture/models.py
> +    homework_teachers_comments = models.CharField(max_length=100)
max_length 改成 1024

2020-11-12 13:26 UTC, DarkKowalski commented on catfood/lecture/models.py
> +    file_usage = models.CharField(max_length=100)
意义不明

2020-11-12 13:26 UTC, DarkKowalski commented on catfood/user/models.py
> +    email = models.CharField(max_length=50)
使用 https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.EmailField

2020-11-12 13:31 UTC, xiongnemo commented on catfood/class/models.py
> +    course_type = models.BooleanField(default=True)
只写 course_type 无法表明是“是否为必修课”

2020-11-12 14:03 UTC, xiongnemo requested changes
阅读 comments

2020-11-12 14:03 UTC, xiongnemo commented on catfood/user/models.py
> +    email = models.CharField(max_length=50)
见

使用 https://docs.djangoproject.com/en/3.1/ref/models/fields/#django.db.models.EmailField

_Originally posted by @DarkKowalski in https://github.com/TJCatFood/backend/pull/12#r522098254_

2020-11-12 14:04 UTC, xiongnemo commented
`.DS_Store` 不应该被包括在 source tree 中

2020-11-12 14:05 UTC, xiongnemo commented
注意整个项目的命名规则
需要对 `courseDatabBase` 重新命名

2020-11-12 16:43 UTC, xiongnemo requested changes
see new requests ;)

2020-11-12 16:43 UTC, xiongnemo commented on catfood/class/models.py
> +    course_start_timestamp = models.DateTimeField()
请帮我将 `course_start_timestamp`  改成 `course_start_time`

2020-11-12 16:43 UTC, xiongnemo commented on catfood/class/models.py
> +    course_end_timestamp = models.DateTimeField()
请帮我将 `course_end_timestamp`  改成 `course_end_time`

2020-11-12 16:43 UTC, xiongnemo commented on catfood/bulletin/models.py
> +    announcement_is_sticky_on_top = models.BooleanField(default=True)
请帮我将 `announcement_is_sticky_on_top` 改成 `announcement_is_pinned`

2020-11-12 18:03 UTC, xiongnemo requested changes
重新评估更改

2020-11-12 18:18 UTC, FWdarling requested changes
见 comments

2020-11-12 18:18 UTC, FWdarling commented on catfood/user/models.py
> +class Invite(models.Model):
用invitation名词命名类更合适

2020-11-18 01:43 UTC, Major-333 commented on catfood/catfood/settings.py
> +    'courseDataBase',
存疑

2020-11-18 01:44 UTC, Major-333 commented on catfood/contest/models.py
> +    question_id = models.ForeignKey('courseDataBase.questionBank', on_delete=models.CASCADE)
app命名统一使用的小驼峰

2020-11-18 01:44 UTC, Major-333 commented on catfood/contest/models.py
> +    question_id = models.ForeignKey('courseDataBase.questionBank', on_delete=models.CASCADE)
app命名统一使用的小驼峰

2020-11-18 01:59 UTC, Major-333 commented on catfood/class/models.py
> +    course_study_time_needed = models.IntegerField
已经讨论过，此处保留原设计

2020-11-18 02:06 UTC, Major-333 commented on catfood/contest/models.py
> +    timestamp = models.DateTimeField()
已经改为auto_now_add=True，如依然不符合要求请回复

2020-11-18 02:08 UTC, Major-333 commented on catfood/contest/models.py
> +    timestamp = models.DateTimeField()
已经改为auto_now_add=True，如依然不符合要求请回复

2020-11-18 02:08 UTC, Major-333 commented on catfood/contest/models.py
> +    timestamp = models.DateTimeField()
已经改为auto_now_add=True

2020-11-18 02:09 UTC, Major-333 commented on catfood/contest/models.py
> +    timestamp = models.DateTimeField()
> filed修改为自动生成的timestamp

已经改为auto_now_add=True，如依然不符合要求请回复

2020-11-18 02:09 UTC, Major-333 commented on catfood/contest/models.py
> +    timestamp = models.DateTimeField()
> filed修改为自动生成的timestamp

已经改为auto_now_add=True

2020-11-18 02:09 UTC, Major-333 commented on catfood/contest/models.py
> +    timestamp = models.DateTimeField()
> 该时间戳为自动生成， 后面field要修改一下

已经改为auto_now_add=True

2020-11-18 02:09 UTC, Major-333 commented on catfood/class/models.py
> +    course_study_time_needed = models.IntegerField
> 学分和课时要么都有默认值 要么都没有
> 如果只是涉及某个学校内开设课程，那就必须设定二者，不要留默认值
> 如果是要给将来发布到网上留扩展， 就都设定一个默认值用于检测

已经讨论过，此处保留原设计

2020-11-18 02:10 UTC, Major-333 commented on catfood/courseDataBase/apps.py
> +    name = 'courseDataBase'
> 命名规则：应使用全小写字母，必要的时候加下划线

app名使用小驼峰

2020-11-20 16:54 UTC, xiongnemo requested changes
there still exists some camelCase variables

2020-11-20 16:54 UTC, xiongnemo commented on catfood/grade/models.py
> +    exam1Point = models.IntegerField(null=True)
naming style

2020-11-20 17:24 UTC, xiongnemo commented
looks good for me

2020-11-20 17:26 UTC, merged